var hierarchy =
[
    [ "UniformClient.Plugins.API", "d5/d12/class_uniform_client_1_1_plugins_1_1_a_p_i.html", null ],
    [ "UniformQueries.API", "df/d75/class_uniform_queries_1_1_a_p_i.html", null ],
    [ "AuthorityController.Data.BanInformation", "dd/de1/struct_authority_controller_1_1_data_1_1_ban_information.html", null ],
    [ "UniformClient.BaseClient", "d4/deb/class_uniform_client_1_1_base_client.html", [
      [ "TestClient.Client", "d6/dac/class_test_client_1_1_client.html", null ],
      [ "UniformClient.Standard.SimpleClient", "d0/d21/class_uniform_client_1_1_standard_1_1_simple_client.html", null ]
    ] ],
    [ "UniformServer.BaseServer", "d7/d32/class_uniform_server_1_1_base_server.html", [
      [ "AuthorityController.AuthorityTestServer.Server", "da/df0/class_authority_controller_1_1_authority_test_server_1_1_server.html", null ],
      [ "QueriesServer.Server", "d2/d9a/class_queries_server_1_1_server.html", null ],
      [ "SessionProvider.Server", "d8/d17/class_session_provider_1_1_server.html", null ],
      [ "UniformServer.Standard.BroadcastingServer", "d5/dac/class_uniform_server_1_1_standard_1_1_broadcasting_server.html", null ],
      [ "UniformServer.Standard.SimpleServer", "db/daa/class_uniform_server_1_1_standard_1_1_simple_server.html", null ]
    ] ],
    [ "PipesProvider.Server.TransmissionControllers.BaseServerTransmissionController", "d0/d5b/class_pipes_provider_1_1_server_1_1_transmission_controllers_1_1_base_server_transmission_controller.html", [
      [ "PipesProvider.Server.TransmissionControllers.BroadcastingServerTransmissionController", "db/df3/class_pipes_provider_1_1_server_1_1_transmission_controllers_1_1_broadcasting_server_transmission_controller.html", null ],
      [ "PipesProvider.Server.TransmissionControllers.ClientToServerTransmissionController", "dc/ddf/class_pipes_provider_1_1_server_1_1_transmission_controllers_1_1_client_to_server_transmission_controller.html", null ],
      [ "PipesProvider.Server.TransmissionControllers.ServerToClientTransmissionController", "d5/d4e/class_pipes_provider_1_1_server_1_1_transmission_controllers_1_1_server_to_client_transmission_controller.html", null ]
    ] ],
    [ "PipesProvider.Client.ClientAPI", "d9/d01/class_pipes_provider_1_1_client_1_1_client_a_p_i.html", null ],
    [ "AuthorityController.API.Collections", "d3/d91/class_authority_controller_1_1_a_p_i_1_1_collections.html", null ],
    [ "UniformServer.Commands", "d3/d12/class_uniform_server_1_1_commands.html", null ],
    [ "AuthorityController.Data.Config", "db/d4a/class_authority_controller_1_1_data_1_1_config.html", null ],
    [ "AuthorityControllerTests.Configurator", "d8/d05/class_authority_controller_tests_1_1_configurator.html", null ],
    [ "UniformClient.Plugins.Constants", "d2/d62/class_uniform_client_1_1_plugins_1_1_constants.html", null ],
    [ "PipesProvider.Security.Crypto", "d6/d06/class_pipes_provider_1_1_security_1_1_crypto.html", null ],
    [ "AuthorityController.Tests.Data", "d5/d06/class_authority_controller_1_1_tests_1_1_data.html", null ],
    [ "PipesProvider.Handlers.DNS", "d4/d27/class_pipes_provider_1_1_handlers_1_1_d_n_s.html", null ],
    [ "PipesProvider.Security.General", "d6/d6b/class_pipes_provider_1_1_security_1_1_general.html", null ],
    [ "PipesProvider.Networking.Info", "d7/d6e/class_pipes_provider_1_1_networking_1_1_info.html", null ],
    [ "PipesProvider.Networking.Routing.Instruction", "d5/d2e/class_pipes_provider_1_1_networking_1_1_routing_1_1_instruction.html", null ],
    [ "UniformClient.Plugins.IPlugin", "d4/d25/interface_uniform_client_1_1_plugins_1_1_i_plugin.html", null ],
    [ "UniformQueries.IQueryHandler", "da/d51/interface_uniform_queries_1_1_i_query_handler.html", [
      [ "AuthorityController.Queries.GET_GUEST_TOKEN", "d0/db0/class_authority_controller_1_1_queries_1_1_g_e_t___g_u_e_s_t___t_o_k_e_n.html", null ],
      [ "AuthorityController.Queries.SET_TOKEN_RIGHTS", "d6/d9d/class_authority_controller_1_1_queries_1_1_s_e_t___t_o_k_e_n___r_i_g_h_t_s.html", null ],
      [ "AuthorityController.Queries.USER_BAN", "d3/d4f/class_authority_controller_1_1_queries_1_1_u_s_e_r___b_a_n.html", null ],
      [ "AuthorityController.Queries.USER_LOGOFF", "db/d2a/class_authority_controller_1_1_queries_1_1_u_s_e_r___l_o_g_o_f_f.html", null ],
      [ "AuthorityController.Queries.USER_LOGON", "de/d4c/class_authority_controller_1_1_queries_1_1_u_s_e_r___l_o_g_o_n.html", null ],
      [ "AuthorityController.Queries.USER_NEW", "d1/d07/class_authority_controller_1_1_queries_1_1_u_s_e_r___n_e_w.html", null ],
      [ "AuthorityController.Queries.USER_NEW_PASSWORD", "d5/d21/class_authority_controller_1_1_queries_1_1_u_s_e_r___n_e_w___p_a_s_s_w_o_r_d.html", null ],
      [ "UniformServer.Queries.GET_PUBLIC_KEY", "da/d43/class_uniform_server_1_1_queries_1_1_g_e_t___p_u_b_l_i_c___k_e_y.html", null ]
    ] ],
    [ "AuthorityController.Locks", "d8/df8/class_authority_controller_1_1_locks.html", null ],
    [ "PipesProvider.Security.LogonConfig", "df/d6d/struct_pipes_provider_1_1_security_1_1_logon_config.html", null ],
    [ "PipesProvider.Security.LSA.LSA_OBJECT_ATTRIBUTES", "dd/dd5/struct_pipes_provider_1_1_security_1_1_l_s_a_1_1_l_s_a___o_b_j_e_c_t___a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "PipesProvider.Security.LSA.LSA_UNICODE_STRING", "d7/df5/struct_pipes_provider_1_1_security_1_1_l_s_a_1_1_l_s_a___u_n_i_c_o_d_e___s_t_r_i_n_g.html", null ],
    [ "PipesProvider.Security.LSA.LsaSecurityWrapper", "de/d2d/class_pipes_provider_1_1_security_1_1_l_s_a_1_1_lsa_security_wrapper.html", null ],
    [ "UniformClient.Plugins.MenuItemMeta", "dd/db0/class_uniform_client_1_1_plugins_1_1_menu_item_meta.html", null ],
    [ "ConsoleDraw.Primitives", "db/d7f/class_console_draw_1_1_primitives.html", null ],
    [ "AuthorityController.Tests.Queries", "d0/d5d/class_authority_controller_1_1_tests_1_1_queries.html", null ],
    [ "PipesProvider.Handlers.Query", "d2/db8/class_pipes_provider_1_1_handlers_1_1_query.html", null ],
    [ "PipesProvider.Client.QueryContainer", "d0/dc9/struct_pipes_provider_1_1_client_1_1_query_container.html", null ],
    [ "UniformQueries.QueryPart", "d5/d61/struct_uniform_queries_1_1_query_part.html", null ],
    [ "AuthorityController.Tests.Regex", "d5/d33/class_authority_controller_1_1_tests_1_1_regex.html", null ],
    [ "PipesProvider.Networking.Routing.RoutingTable", "d3/d3a/class_pipes_provider_1_1_networking_1_1_routing_1_1_routing_table.html", null ],
    [ "AuthorityController.Data.SaltContainer", "d2/d57/class_authority_controller_1_1_data_1_1_salt_container.html", null ],
    [ "PipesProvider.Server.ServerAPI", "d5/d17/class_pipes_provider_1_1_server_1_1_server_a_p_i.html", null ],
    [ "PipesProvider.Handlers.Service", "dd/d9c/class_pipes_provider_1_1_handlers_1_1_service.html", null ],
    [ "AuthorityController.Tests.Session", "d9/ddb/class_authority_controller_1_1_tests_1_1_session.html", null ],
    [ "AuthorityController.Session", "d6/d4b/class_authority_controller_1_1_session.html", null ],
    [ "AuthorityController.Data.TokenInfo", "d6/d68/class_authority_controller_1_1_data_1_1_token_info.html", null ],
    [ "AuthorityController.API.Tokens", "d7/daa/class_authority_controller_1_1_a_p_i_1_1_tokens.html", null ],
    [ "PipesProvider.Client.TransmissionLine", "da/d0e/class_pipes_provider_1_1_client_1_1_transmission_line.html", null ],
    [ "AuthorityController.Data.User", "d8/d02/class_authority_controller_1_1_data_1_1_user.html", null ],
    [ "AuthorityController.API.Users", "da/d48/class_authority_controller_1_1_a_p_i_1_1_users.html", null ],
    [ "AuthorityController.API.Validation", "dc/d46/class_authority_controller_1_1_a_p_i_1_1_validation.html", null ]
];